### ISSUE TITLE
Scipt not working

### ISSUE THREAD

**Issue by FcoMarcosMAbreu** [PalmerAL/min-link-tooltip-userscript#1]
Min is up-to-date an user script is enabled.

**Comment by PalmerAL** [comment]
It works for me; where did you save the script? Did you restart Min after saving it?

**Comment by FcoMarcosMAbreu** [comment]
Yes. I'd restart it. I did saved in ~/.config/Min/userscripts/link-tooltip.js. Is there any information that I can send to help?

**Comment by PalmerAL** [comment]
This script is still using the old (from 1.14 and below) userscript format, so it needs to be saved as `global.js`. I'll go ahead and update it to the new format.

**Comment by PalmerAL** [comment]
Done in f887f65a147b7620945ac83dbdc3e4239cb68565; if you use the updated version you should be able to save it with any file name.

**Comment by FcoMarcosMAbreu** [comment]
Worked! Thank you very much!
