### ISSUE TITLE
z-index

### ISSUE THREAD

**Issue by michaelhobbs** [PalmerAL/min-link-tooltip-userscript#2]
Hi, thanks for the cool userscript, I like to see what a link target is before clicking it.

One thing I noticed was that the tooltip has no z-index and can be hidden below other fixed position elements on a page. eg: on youtube homepage.

Locally I set it to `z-index: 2147483647;`.

Just letting you know. Thanks again!

![Screenshot from 2021-01-10 23-38-17](https://user-images.githubusercontent.com/6884094/104137453-17d8ff00-539d-11eb-83d3-b632fa521e9e.png)

**Comment by PalmerAL** [comment]
Thanks! Fixed in ffabe47292e496f2f1d8616b80fff49b99fc7240.
